### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by 0xe25** [memir0/CTFd-Ldap#1]
Hello , 
Thank you for your amazing work. 
Can you please give me the instructions on how to install and configure the plugins.

I copied all file into the plugins/CTFd_Ldap directory and then config LDAP ( `__init__.py`) but does not work for me.

**Comment by emirdero** [comment]
The plugin requires you to change the settings so that they correspond to the ldap server you are trying to connect to. These are the 'settings' object in __init__.py. If you have already done this, can you show me an example of an ldap entry on your system? It might be different from the system I made this for.

**Comment by 0xe25** [comment]
My faculty LDAP only support ldaps (636).

This is  DN users example: 
> uid=b2020210018,ou=Users,ou=2020,ou=Geology,ou=Science,ou=Faculty,dc=mydomain

```python
...
    # Change these settings to correspond to your ldap server
    settings = {
        'name': "Login",
        'host': 'ldap.example.com',
        'port': 636,
        'encryption': 'none',
        'base_dn': 'ou=Faculty,dc=mydomain',
        'type_dn': 'ou=Users',
        'request': "(uid={})",
        'prefix': "",
        'require_cert': True
    }
...
```

**Comment by emirdero** [comment]
Is your host set to ldap.example.com? That might be the issue. As for the ldaps, my plugin uses tls. Do you get any error messages?

**Comment by 0xe25** [comment]
My server is not named `ldap.example.com`. I changed the name when using it with the real machine. 
I checked the traffic on the LDAP machine and found no traffic (no error show) from ctfd.

I used Docker for ctfd.  No problem show in web page or command line log.
<img width="360" alt=" 2563-07-06 at 18 12 33" src="https://user-images.githubusercontent.com/60555504/86587787-7d929b80-bfb4-11ea-943a-abb2d776f814.png">

*  docker container logs -f ctfd_ctfd_1

![ 2563-07-06 at 18 06 40](https://user-images.githubusercontent.com/60555504/86587435-ca29a700-bfb3-11ea-8a0c-888eedc8a9d5.png)

```
192.168.16.1 - - [06/Jul/2020:11:07:20 +0000] "POST /login HTTP/1.0" 403 3258 "https://ctf2020.example.com/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
192.168.16.1 - - [06/Jul/2020:11:07:20 +0000] "GET /events HTTP/1.1" 403 3258 "https://ctf2020.example.com/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
```

**Comment by emirdero** [comment]
I see that you are using gunicorn in the docker (default for the dockerfile provided with ctfd). Gunicorn is for production and therefore isn't that helpful with errors in development. Try to run it with 'flask run' without docker and look for errors when logging in.

**Comment by emirdero** [comment]
Any updates? @0xe25

**Comment by 0xe25** [comment]
`flask run`  does not report any errors.

**Comment by emirdero** [comment]
It might be a firewall blocking it. I have created a small test script with better output you can use to test: https://github.com/memir0/ldap-test/tree/master

**Comment by 0xe25** [comment]
Thank you for taking the time to create test script. The program is very useful to me. I can test it by myself.

This configuration can authenticated with my LDAP, unfortunately when applied to CTFd-Ldap still has same previous  problem. Meaning no ldap traffic out  to the ldap server.

```python
login_info = {
    'username': "uid=myid,ou=Users,ou=2020,ou=Civil Engineering,ou=Engineering,ou=Faculty,dc=mydomain",
    'password': "PaSsWoRd"
}

settings = {
    'name': "Ldap",
    'host': 'ldap.example.com',
    'port': 636,
    'encryption': 'ssl',
    'base_dn': "dc=mydomain",
    'request': "(uid={})",
    'prefix': "",
    'require_cert': True
}

login = login_info["username"].strip().lower()
login_dn = login
password = login_info["password"]
```

* output
```
[user@v ~]$ python3 test.py 
connection to ldap

Connected
RESPONSE: 
[]
[user@v ~]$ 
```

**Comment by emirdero** [comment]
Response is not supposed to be empty.
I see that you are using the entire dn as the username. The login value is wrong in your code as a result, it needs to be changed to 'login = "myid" '. I'm guessing that's why response is empty.

It is however odd that you aren't seeing traffic when you apply it to CTFd-Ldap, in my use-case I could only connect to the ldap server if I was on the same network, that might be the case with you aswell if you are using external hosting.

**Comment by emirdero** [comment]
Any updates? @0xe25

**Comment by 0xe25** [comment]
No luck. I'm stuck with this problem.

* CTFd-Ldap(`__init__.py`)
```
    settings = {
        'name': "example",
        'host': 'ldap.example.com',
        'port': 636,
        'encryption': 'ssl',
        'base_dn': 'dc=example,dc=com',
        'type_dn': 'ou=users',
        'request': "(uid={})",
        'prefix': "",
        'require_cert': True
    }
```

* ctfd log
```
connection to ldap
ERROR  {'result': 34, 'description': 'invalidDNSyntax', 'dn': '', 'message': 'invalid DN', 'referrals': None, 'saslCreds': None, 'type': 'bindResponse'}
[07/21/2020 15:43:21] 192.168.16.1 - submitted invalid password for None
[07/21/2020 15:43:21] 192.168.16.1 - submitted invalid password for None
```

* Ldap log
```
5f170d9f conn=2812 fd=70 ACCEPT from IP=172.17.0.1:51620 (IP=0.0.0.0:636)
5f170d9f conn=2812 fd=70 TLS established tls_ssf=256 ssf=256
5f170d9f conn=2812 op=0 SRCH base="" scope=0 deref=3 filter="(objectClass=*)"
5f170d9f conn=2812 op=0 SRCH attr=altServer namingContexts supportedControl supportedExtension supportedFeatures supportedCapabilities supportedLdapVersion supportedSASLMechanisms vendorName vendorVersion subschemaSubentry * + +
5f170d9f conn=2812 op=0 SEARCH RESULT tag=101 err=0 nentries=1 text=
5f170d9f conn=2812 op=1 SRCH base="cn=Subschema" scope=0 deref=3 filter="(objectClass=subschema)"
5f170d9f conn=2812 op=1 SRCH attr=objectClasses attributeTypes ldapSyntaxes matchingRules matchingRuleUse dITContentRules dITStructureRules nameForms createTimestamp modifyTimestamp * +
5f170d9f conn=2812 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
5f170d9f conn=2812 op=2 do_bind: invalid dn (sk)
5f170d9f conn=2812 op=2 RESULT tag=97 err=34 text=invalid DN
```

**Comment by emirdero** [comment]
Seems like you are close to the finish line. I encountered the same error code while developing the plugin. To fix it I had to play around with the login_dn until it worked, I know you said "uid=myid,ou=Users,ou=2020,ou=Civil Engineering,ou=Engineering,ou=Faculty,dc=mydomain" was the syntax, so 'base_dn' should maybe be "ou=2020,ou=Civil Engineering,ou=Engineering,ou=Faculty"? You might wan't to change 'type_dn' to 'ou=Users' in case it's case sensitive.

**Comment by 0xe25** [comment]
Thank you very much. It looks like I'm close to fixing the problem. Right now I'm working on some error. 

```
ERROR [CTFd] Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/CTFd/CTFd/plugins/CTFd-Ldap/__init__.py", line 134, in login
    user = Users(name=login, email=email, password=dummy_password)
UnboundLocalError: local variable 'email' referenced before assignment
connection to ldap
Connected
```

**Comment by emirdero** [comment]
You need to define a user email. In my system it gets the users email from the ldap server. You could use a random email too, ctfd has no real use for the email with this plugin. It needs to be defined before line 134 as the error says

**Comment by 0xe25** [comment]
Solved, I can login by using the Ldap password. Thank you for all your assistance.

**Comment by emirdero** [comment]
You're welcome 😁
