### ISSUE TITLE
ModuleNotFoundError: No module named 'ldap3'

### ISSUE THREAD

**Issue by ab0l3th** [memir0/CTFd-Ldap#2]
I was testing out your LDAP plugin and i have LDAP3 installed and i am getting this errror.

 2021-10-13 20:41:07 0 [Note] InnoDB: Buffer pool(s) load completed at 211013 20:41:07
ctfd_1   | Waiting for mysql+pymysql://ctfd:ctfd@db to be ready
ctfd_1   | mysql+pymysql://ctfd:ctfd@db is ready
ctfd_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
ctfd_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "manage.py", line 14, in <module>
ctfd_1   |     app = create_app()
ctfd_1   |   File "/opt/CTFd/CTFd/__init__.py", line 305, in create_app
ctfd_1   |     init_plugins(app)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/__init__.py", line 202, in init_plugins
ctfd_1   |     module = importlib.import_module(module, package="CTFd.plugins")
ctfd_1   |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
ctfd_1   |     return _bootstrap._gcd_import(name[level:], package, level)
ctfd_1   |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
ctfd_1   |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
ctfd_1   |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
ctfd_1   |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
ctfd_1   |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
ctfd_1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/CTFd-Ldap/__init__.py", line 10, in <module>
ctfd_1   |     import ldap3
ctfd_1   | ModuleNotFoundError: No module named 'ldap3'

root@hackclub-ctfd:/usr/bin# pip install ldap3
Requirement already satisfied: ldap3 in /usr/local/lib/python3.9/dist-packages (2.7)
Requirement already satisfied: pyasn1>=0.1.8 in /usr/lib/python3/dist-packages (from ldap3) (0.4.8)
root@hackclub-ctfd:/usr/bin# pip3 install ldap3
Requirement already satisfied: ldap3 in /usr/local/lib/python3.9/dist-packages (2.7)
Requirement already satisfied: pyasn1>=0.1.8 in /usr/lib/python3/dist-packages (from ldap3) (0.4.8)

It has to be a Python3 issue I would guess.  

OS=Linux 5.11.0-37-generic #41-Ubuntu SMP Mon Sep 20 16:39:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by emirdero** [comment]
you are installing it with pip for the root user. If you are running ctfd with another user or virtual environment the package will not be available

**Comment by ab0l3th** [comment]
I appreciate you taking time to reply.  The reason i was running it as root was due to the error:

ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

Even running as my user with root access it still gets the same error...i will forgoe the LDAP integration for now.
